const actionTypes = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  SHOW_MODAL_ANKET: "SHOW_MODAL_ANKET",
  CLOSE_MODAL_ANKET: "CLOSE_MODAL_ANKET",
  ADD_NOTE: "ADD_NOTE"

};

export default actionTypes;